[mypy]
explicit_package_bases = True
namespace_packages = True

[mypy-aiavatar.*]
ignore_missing_imports = True

[mypy-moonshine_voice.*]
ignore_missing_imports = True

[mypy-faster_whisper.*]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-twitchAPI.*]
ignore_missing_imports = True

[mypy-google.genai.*]
ignore_missing_imports = True

[mypy-dotenv.*]
ignore_missing_imports = True
