[project]
name = "parcera"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "aiavatar>=0.8.7",
  "faster-whisper>=1.2.1",
  "google-genai>=1.62.0",
  "openai-whisper>=20250625",
  "python-dotenv>=1.2.1",
  "setuptools>=82.0.0",
  "httpx>=0.28.1",
  "PyYAML>=6.0.1",
  "fastapi>=0.129.0",
  "uvicorn>=0.40.0",
  "openai>=2.20.0",
  "google-cloud-speech>=2.36.1",
  "azure-cognitiveservices-speech>=1.48.1",
]
